# Site settings
title: "Your Title Here"
description: "A placeholder poetry blog."
baseurl: "/poetry"
url: "http://apothecarymark.github.io/poetry"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          value: false
  media: "images"
  ignore:
    - /_includes
    - /_layouts
    - /css
    - /images
    - README.md
    - .gitignore
    - feed.xml
    - LICENSE
    - index.html
    # REMOVE THIS LINE TO EDIT THE CONFIG
    - _config.yml

# Links
links:
  - title: "about"
    url: /about
  # - title: "twt"
  #  url: http://twitter.com/alixedi
  # - title: "git"
  #  url: http://github.com/alixedi
  # - title: "rss"
  #  url: /feed.xml
  - title: "blog"
    url: "/"
